# Generated by Django 5.2.1 on 2025-10-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sujet',
            field=models.CharField(default='', max_length=200, verbose_name='Sujet'),
        ),
    ]
